name: Update and publish

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Install Python dependencies
        run: pip3 install -U PyGithub

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch last run data
        env:
          OWNER: ${{ github.event.repository.owner.login }}
          REPO_NAME: ${{ github.event.repository.name }}
        continue-on-error: true
        run: |
          mkdir cache
          wget --progress=dot https://$OWNER.github.io/$REPO_NAME/data_dump.json.bz2 -O cache/data_dump.json.bz2
          bunzip2 cache/data_dump.json.bz2

      - name: Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./update_pr.py
          bzip2 -c cache/data_dump.json > public/data_dump.json.bz2

      - name: Crunch
        run: |
          ./crunch_data.py

      - name: Setup pages
        uses: actions/configure-pages@v3

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
